// Generated by CoffeeScript 1.4.0
var app;

app = angular.module('showdownEd', ['ngSanitize']);

app.controller('Editor', function($scope, $http, $sanitize) {
  var converter, updateHTML;
  converter = new Showdown.converter();
  $scope.haveFileSelected = false;
  $scope.files = [
    {
      name: 'demo.md'
    }, {
      name: 'demo2.md'
    }
  ];
  updateHTML = function(md) {
    var html;
    html = converter.makeHtml(md);
    $scope.currentMarkdown = md;
    return $scope.currentHtml = html;
  };
  $scope.selectFile = function() {
    var fn;
    fn = $scope.selectedFile.name;
    return $http({
      method: 'GET',
      url: 'markdown/' + fn
    }).success(function(data, status, headers, config) {
      $scope.haveFileSelected = true;
      return updateHTML(data);
    });
  };
  return true;
});
